baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Site'
copyright = 'Example. All rights reserved.'

[params]
subtitle = 'Subtitle in Header'
metaDescription = 'Meta Description'
footerLinks = [
	['Example', 'https://example.com'],
	['GitHub', 'https://github.com'],
]

[taxonomies]
tag = "tags"
