baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Site'
copyright = 'Example. All rights reserved.'

[params]
contactFormHandlerURL = 'URL to the POST endpoint for contact form submission'
hCaptchaSiteKey = 'Your hCaptcha Site Key'
subtitle = 'Subtitle in Header'
metaDescription = 'Meta Description'
footerLinks = [
	['Example', 'https://example.com'],
	['GitHub', 'https://github.com'],
]

[taxonomies]
tag = "tags"
